### ISSUE TITLE
Pipeline Run created but no status is shown

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kfp-operators#345]
### Bug Description

When creating a pipeline from the UI or from a Notebook, the pipeline run does not succeed. Yet, we cannot see the status of the pipeline run.
The workflow gets created, but it is stuck with no Status.

### To Reproduce

1. juju deploy kubeflow --trust --channel=latest/edge
2. Create a Pipeline from the UI or Notebook

### Environment

microk8s 1.25-strict/stable
juju 3.1/stable

### Relevant log output

```shell
kubectl logs kfp-schedwf-0 -nkubeflow
2023-10-04T13:40:12.554Z [container-agent] 2023-10-04 13:40:12 INFO juju-log Executing component: 'kfp-schedwf-pebble-service'
2023-10-04T13:40:12.604Z [container-agent] 2023-10-04 13:40:12 INFO juju-log PebbleServiceComponent.get_layer executing
2023-10-04T13:40:12.625Z [container-agent] 2023-10-04 13:40:12 ERROR juju-log execute_components caught unhandled exception when executing configure_charm for kfp-schedwf-pebble-service
2023-10-04T13:40:12.625Z [container-agent] Traceback (most recent call last):
2023-10-04T13:40:12.625Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-schedwf-0/charm/venv/ops/pebble.py", line 1571, in _request_raw
2023-10-04T13:40:12.625Z [container-agent]     response = self.opener.open(request, timeout=self.timeout)
2023-10-04T13:40:12.625Z [container-agent]   File "/usr/lib/python3.8/urllib/request.py", line 531, in open
2023-10-04T13:40:12.625Z [container-agent]     response = meth(req, response)
2023-10-04T13:40:12.625Z [container-agent]   File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
2023-10-04T13:40:12.625Z [container-agent]     response = self.parent.error(
2023-10-04T13:40:12.625Z [container-agent]   File "/usr/lib/python3.8/urllib/request.py", line 569, in error
2023-10-04T13:40:12.625Z [container-agent]     return self._call_chain(*args)
2023-10-04T13:40:12.625Z [container-agent]   File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
2023-10-04T13:40:12.625Z [container-agent]     result = func(*args)
2023-10-04T13:40:12.625Z [container-agent]   File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
2023-10-04T13:40:12.625Z [container-agent]     raise HTTPError(req.full_url, code, msg, hdrs, fp)
2023-10-04T13:40:12.625Z [container-agent] urllib.error.HTTPError: HTTP Error 400: Bad Request
2023-10-04T13:40:12.625Z [container-agent] 
2023-10-04T13:40:12.625Z [container-agent] During handling of the above exception, another exception occurred:
2023-10-04T13:40:12.625Z [container-agent] 
2023-10-04T13:40:12.625Z [container-agent] Traceback (most recent call last):
2023-10-04T13:40:12.625Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-schedwf-0/charm/venv/charmed_kubeflow_chisme/components/charm_reconciler.py", line 92, in reconcile
2023-10-04T13:40:12.625Z [container-agent]     component_item.component.configure_charm(event)
2023-10-04T13:40:12.625Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-schedwf-0/charm/venv/charmed_kubeflow_chisme/components/component.py", line 50, in configure_charm
2023-10-04T13:40:12.625Z [container-agent]     self._configure_unit(event)
2023-10-04T13:40:12.625Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-schedwf-0/charm/venv/charmed_kubeflow_chisme/components/pebble_component.py", line 131, in _configure_unit
2023-10-04T13:40:12.625Z [container-agent]     self._update_layer()
2023-10-04T13:40:12.625Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-schedwf-0/charm/venv/charmed_kubeflow_chisme/components/pebble_component.py", line 140, in _update_layer
2023-10-04T13:40:12.625Z [container-agent]     container.add_layer(self.container_name, new_layer, combine=True)
2023-10-04T13:40:12.625Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-schedwf-0/charm/venv/ops/model.py", line 1942, in add_layer
2023-10-04T13:40:12.625Z [container-agent]     self._pebble.add_layer(label, layer, combine=combine)
2023-10-04T13:40:12.625Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-schedwf-0/charm/venv/ops/pebble.py", line 1855, in add_layer
2023-10-04T13:40:12.625Z [container-agent]     self._request('POST', '/v1/layers', body=body)
2023-10-04T13:40:12.625Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-schedwf-0/charm/venv/ops/pebble.py", line 1538, in _request
2023-10-04T13:40:12.625Z [container-agent]     response = self._request_raw(method, path, query, headers, data)
2023-10-04T13:40:12.625Z [container-agent]   File "/var/lib/juju/agents/unit-kfp-schedwf-0/charm/venv/ops/pebble.py", line 1582, in _request_raw
2023-10-04T13:40:12.625Z [container-agent]     raise APIError(body, code, status, message)
2023-10-04T13:40:12.625Z [container-agent] ops.pebble.APIError: plan must define "command" for service "controller"
```

**Comment by DnPlas** [comment]
Should be fixed by https://github.com/canonical/argo-operators/pull/141

**Comment by NohaIhab** [comment]
after testing again, this issue persisted.
The workflow object gets created, then it gets stuck with status
```
status:
  finishedAt: null
  startedAt: null
```
and the pods never get created in the user's namespace.
since `argo-controller` is responsible for creating these pods where the pipeline runs, the issue is potentially with the `argo-controller` charm.

Looking at the entrypoint of `argo-controller`, the Pebble service command is set to:
```
                        "command": (
                            "workflow-controller "
                            "--configmap "
                            f"{ARGO_CONTROLLER_CONFIGMAP} "
                            "--executor-image "
                            f"{self.model.config[EXECUTOR_IMAGE_CONFIG_NAME]} "
                            "--namespaced"
                        )
```
the `--namespaced` flag is the issue here: with namespace scope configuration, it allows workflows to run only in the namespace where Argo is installed - in our case the `kubeflow` namespace.

Our source of truth is upstream manifests, and in their manifests they [do not use namespaced configuration](https://github.com/kubeflow/manifests/blob/master/apps/pipeline/upstream/env/platform-agnostic-multi-user/kustomization.yaml#L8), so we should not have the `--namespaced` in the `argo-controller` entrypoint.

**Comment by NohaIhab** [comment]
moving to https://github.com/canonical/argo-operators since it's an issue with an argo charm.
